version: "3"

services:
   nginx:
      build:
         context: .
         dockerfile: nginx/Dockerfile.nginx
      ports:
         - 8080:80
      networks:
         - knet
      tty: true
      volumes:
         - ./app/:/var/www/html/
         - ./logs/nginx/:/var/log/nginx/
   php:
      build:
         context: .
         dockerfile: php/Dockerfile
      networks:
         - knet
      volumes:
         - ./app/:/var/www/html/
         - ./logs/php.log/:/var/log/fpm-php.www.log/

networks:
   knet:
      driver: bridge
